runtime: python39

instance_class: F1

env_variables:
  GITHUB_CLIENT_ID: 'Iv1.7a135c29c0be40e9'
  GITHUB_CLIENT_SECRET: '6f46810a3a9d10a278fe768056caf86ed2abb545'
  GOOGLE_CLIENT_ID: '936981319687-j4b1egeiqjt58g0ei2dc19ga9j3b3ad5.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRECT: '4KpQcnXGopJDXkTJkSHXH65M'
  DB_USER: 'postgres'
  DB_PASS: 'K0ghxr4Ng1tIArjn'
  DB_NAME: 'hackforgood'
  DB_CONNECTION: 'hackforgood-288806:us-central1:hackforgood-pg'

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
